fix: Fix for source-map v0.7
ktsn/vue-hot-reload-loader pull request #13
Opened 2018-09-07 01:59 UTC by DanSnow

In [source-map](https://github.com/mozilla/source-map) v0.7, they use wasm to speed up `SourceMapConsumer`.
And the constructor is now returning a Promise.
Also bump acorn version to support object rest spread.
And I notice that `babel-eslint` is unnecessary so I just remove it.

**Notice**: This PR include a **breaking change**
It will require node version >= 8.0.0

If you don't want to include this breaking change.
I can rewrite it with Promise.then.

2018-09-22 11:27 UTC, ktsn requested changes
Can we update travis config to use Node 8?

2018-09-23 00:10 UTC, DanSnow commented
Done

2018-09-23 01:27 UTC, ktsn approved these changes

2018-09-23 01:28 UTC, merged

2018-09-23 01:28 UTC, ktsn commented
Thanks!