Add support for sourcemap
ktsn/vue-hot-reload-loader pull request #5
Opened 2017-03-21 18:18 UTC by Toilal

Close #4

Well, I dive deep into sourcemap generation to understand how to implement this, bit it seems to be the right way to support sourcemap generated by any previous loader in the chain. 

Tested with TypeScript.

2017-03-21 18:21 UTC, Toilal commented
I'll fix build and make more manual tests tomorrow.

2017-03-21 22:14 UTC, Toilal commented
Build fixed, and works on TypeScript and ES6 using #inline-source-map.

2017-03-22 13:46 UTC, ktsn requested changes
I think we should consider one more case - when previous source map does not exist even though the user enables source map. (e.g. there are no loader before this loader)

We can use `this.sourceMap` whether we should output source map.
https://webpack.js.org/api/loaders/#sourcemap

2017-03-22 13:46 UTC, ktsn commented on lib/index.js
> +const SourceMapGenerator = sourceMap.SourceMapGenerator
Can we remove this line since it's not used?

2017-03-22 13:46 UTC, ktsn commented on lib/index.js
> +  if (hasComponent) {
I prefer to negate this condition and `return` in this block early so that we can reduce the nesting level 🙂

2017-03-22 14:28 UTC, Toilal commented
Should be ok now. Thanks for the really good review !

2017-03-22 14:29 UTC, Toilal commented on lib/index.js
> +    sourceType: 'module',
I also think I can remove locations and sourceFile option when this.sourceMap is falsy.

2017-03-22 14:49 UTC, ktsn commented
@Toilal Looks great. Can we fix the lint error? 🙂

2017-03-22 15:15 UTC, Toilal commented
Fixed

2017-03-22 15:23 UTC, ktsn approved these changes

2017-03-22 15:24 UTC, ktsn commented
Thanks. Great work! 👍

2017-03-22 15:24 UTC, merged